datalink(linux): add feature to pass the fd (socket) to ::channel()
libpnet/libpnet pull request #584
Opened 2022-09-12 13:02 UTC by Martichou

This can be useful if the caller want to manipulate the socket differently at creating. 
For example setting a BPF filter on the socket before passing it in the channel:

```
datalink::linux::channel(interface, config, socket_fd)
```

Signed-off-by: Martin Andre <martin.andre@tessares.net>

2023-02-03 14:22 UTC, mrmonday requested changes

2023-02-03 14:22 UTC, mrmonday commented on pnet_datalink/src/lib.rs
> +    socket: i32
I think this should be part of the `Config` struct, rather than an additional argument.

2023-02-03 14:22 UTC, mrmonday commented on pnet_datalink/src/linux.rs
> +    #[cfg(not(feature = "psocket"))]
I don't think this should be feature gated - it should be configurable at runtime using the `Config` struct - if the socket is already set then we skip this setup.

2024-01-13 21:49 UTC, Martichou commented
Hey @mrmonday , sorry for the very very late reply and update on this. Just came back to this and still think this can be helpful to have in the lib.

The tests failing seems to not be linked with the change, can they be ignored? Or any idea?

2024-05-30 16:52 UTC, mrmonday commented
I've just rebased this. There are a couple of white space issues but if CI passes I'll fix that and get this merged in.

2024-05-30 17:06 UTC, mrmonday commented
Thanks! Sorry this took so long.

2024-05-30 17:06 UTC, merged